apiVersion: apps/v1
kind: Deployment
metadata:
  name: jxwafnode
  labels:
    app.kubernetes.io/name: jxwafnode
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: jxwafnode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jxwafnode
    spec:
      hostNetwork: true
      containers:
        - name: jxwafnode
          image: hub.wusong.com/library/devopsutilstools/jxwaf-node:2022-RC3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 443
          env:
            - name: ENV_INIT
              value: "--api_key=c089bd81-b8e8-480c-ba90-8451d4096b06 --api_password=8f712e10-cc3f-4c71-b2c8-76049d6b20aa --waf_server=http://192.168.25.105:8080"
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - "sleep 180"
          resources:
            limits:
              cpu: 2048m
              memory: 4096Mi
            requests:
              cpu: 512m
              memory: 2048Mi
      nodeSelector:
        jxwafnode: jxwafnode
# kubectl label nodes 192.168.25.107 192.168.25.108 192.168.25.109 jxwafnode=jxwafnode
# kubectl set image --namespace jxwaf deployments jxwafnode jxwafnode=hub.wusong.com/library/devopsutilstools/jxwaf-node:2022-RC3
